import {
  UserProfile,
  Incident,
  SafetyZone,
  Responder,
  ServiceLocation,
  LostFoundItem,
  TouristGroup,
  GroupMember,
  AppNotification,
  EmergencyContact,
  TouristProfile,
} from '../types';

export const MOCK_USERS: Record<string, UserProfile> = {
  tourist: {
    id: '11111111-1111-1111-1111-111111111111',
    email: 'elena.rostova@example.com',
    full_name: 'Elena Rostova',
    role: 'tourist',
    phone: '+1 (555) 234-8901',
    nationality: 'Canada',
    passport_or_id_number: 'CA-9823411',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    verification_status: 'verified',
  },
  authority: {
    id: '22222222-2222-2222-2222-222222222222',
    email: 'inspector.shinde@globalgennie.gov',
    full_name: 'Inspector Rajiv Shinde',
    role: 'authority',
    phone: '+91 22 2757 8888',
    nationality: 'India',
    passport_or_id_number: 'IND-POL-NM902',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    verification_status: 'verified',
  },
  responder: {
    id: '33333333-3333-3333-3333-333333333333',
    email: 'officer.patil@touristpolice.org',
    full_name: 'Officer Vikram Patil',
    role: 'responder',
    phone: '+91 98200 11223',
    nationality: 'India',
    passport_or_id_number: 'NM-TP-7712',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    verification_status: 'verified',
  },
  hotel_operator: {
    id: '44444444-4444-4444-4444-444444444444',
    email: 'thepark.concierge@luxuryhotels.com',
    full_name: 'The Park Navi Mumbai Concierge Desk',
    role: 'hotel_operator',
    phone: '+91 22 6758 9000',
    nationality: 'India',
    passport_or_id_number: 'HTL-NM-108',
    avatar_url: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=150&auto=format&fit=crop&q=80',
    verification_status: 'verified',
  },
};

export const MOCK_TOURIST_PROFILE: TouristProfile = {
  user_id: '11111111-1111-1111-1111-111111111111',
  hotel_name: 'The Park Navi Mumbai (CBD Belapur)',
  hotel_room_no: 'Suite 402',
  tour_operator_name: 'Navi Mumbai Coastal & Heritage Expeditions',
  primary_language: 'en',
  blood_group: 'O+',
  medical_conditions: 'Mild Asthma, Carries Ventolin Inhaler',
  allergies: 'Penicillin, Peanuts',
  itinerary_notes: 'Vashi & Palm Beach Road (Day 1-2), Kharghar Hills (Day 3), Belapur Fort & Sagar Vihar (Day 4-5)',
  last_known_lat: 19.0330,
  last_known_lng: 73.0297,
  is_safe_status: true,
};

export const MOCK_EMERGENCY_CONTACTS: EmergencyContact[] = [
  {
    id: 'ec-1',
    user_id: '11111111-1111-1111-1111-111111111111',
    name: 'David Rostova',
    relationship: 'Spouse',
    phone: '+1 (555) 890-1234',
    email: 'david.rostova@example.com',
    is_primary: true,
  },
  {
    id: 'ec-2',
    user_id: '11111111-1111-1111-1111-111111111111',
    name: 'Canadian Consulate General Mumbai 24/7',
    relationship: 'Consular Assistance',
    phone: '+91 22 6749 4444',
    email: 'mumbai.consular@international.gc.ca',
    is_primary: false,
  },
  {
    id: 'ec-3',
    user_id: '11111111-1111-1111-1111-111111111111',
    name: 'The Park Hotel 24h Emergency Desk',
    relationship: 'Accommodation Host',
    phone: '+91 22 6758 9000',
    email: 'security@theparknavimumbai.com',
    is_primary: false,
  },
];

export const MOCK_RESPONDERS: Responder[] = [
  {
    id: 'resp-1',
    name: 'Unit Alpha-1 (Officer Vikram Patil)',
    agency_name: 'Navi Mumbai Tourist Quick Response Team',
    agency_type: 'tourist_police',
    badge_number: 'NM-TP-7712',
    phone: '+91 98200 11223',
    status: 'available',
    current_lat: 19.0740,
    current_lng: 72.9985,
  },
  {
    id: 'resp-2',
    name: 'Emergency Medical Unit Bravo',
    agency_name: 'Apollo Emergency Trauma Ambulance (Belapur)',
    agency_type: 'medical',
    badge_number: 'APO-EMS-302',
    phone: '+91 22 6280 6280',
    status: 'available',
    current_lat: 19.0222,
    current_lng: 73.0368,
  },
  {
    id: 'resp-3',
    name: 'Palm Beach Highway Patrol Unit 4',
    agency_name: 'Nerul Police Station Rapid Patrol',
    agency_type: 'police',
    badge_number: 'PB-104',
    phone: '+91 22 2770 0100',
    status: 'available',
    current_lat: 19.0350,
    current_lng: 73.0200,
  },
];

export const MOCK_SAFETY_ZONES: SafetyZone[] = [
  {
    id: 'zone-1',
    name: 'Vashi Sector 17 & Palm Beach Safe Corridor',
    description: 'High police presence, 24/7 tourist assistance kiosks, CCTV surveillance, well-lit pedestrian corridors',
    zone_type: 'safe_haven',
    risk_level: 'safe',
    center_lat: 19.0748,
    center_lng: 72.9978,
    radius_meters: 900,
    warning_message: 'Safe Zone: 24/7 Navi Mumbai tourist police patrol and surveillance active.',
    instructions: 'Follow illuminated pedestrian avenues and utilize designated tourist assistance points.',
    is_active: true,
  },
  {
    id: 'zone-2',
    name: 'Kharghar Hills & Waterfall Monsoon Advisory Zone',
    description: 'Steep trekking slopes, dense forest trails, increased slipping hazard during wet monsoon conditions.',
    zone_type: 'hazard_zone',
    risk_level: 'warning',
    center_lat: 19.0520,
    center_lng: 73.0720,
    radius_meters: 750,
    warning_message: 'Warning: Slippery rocky terrain and unpaved forest trails.',
    instructions: 'Stay on marked walking trails, wear gripped footwear, avoid edges near waterfall streams.',
    is_active: true,
  },
  {
    id: 'zone-3',
    name: 'JNPT Transit Heavy Vehicle Caution Corridor',
    description: 'Heavy container freight transit and high-speed commercial traffic along port expressway.',
    zone_type: 'hazard_zone',
    risk_level: 'danger',
    center_lat: 18.9500,
    center_lng: 72.9500,
    radius_meters: 800,
    warning_message: 'High Danger: Heavy container truck movement & restricted pedestrian crossing.',
    instructions: 'Use overhead pedestrian skywalks only. Do not attempt road crossing across expressway.',
    is_active: true,
  },
];

export const MOCK_SERVICE_LOCATIONS: ServiceLocation[] = [
  {
    id: 'srv-1',
    name: 'Navi Mumbai Tourist Police Headquarters',
    category: 'tourist_police',
    phone: '+91 22 2757 8888',
    address: 'CBD Belapur, Sector 11, Navi Mumbai',
    latitude: 19.0185,
    longitude: 73.0420,
    is_24_7: true,
    languages_spoken: ['English', 'Hindi', 'Marathi', 'French', 'German'],
    notes: '24/7 dedicated foreign tourist helpline, lost passport FIR processing, verified emergency support.',
  },
  {
    id: 'srv-2',
    name: 'Apollo Hospitals Navi Mumbai (Level-1 Trauma Center)',
    category: 'hospital',
    phone: '+91 22 6280 6280',
    address: 'Parsik Hill Road, Sector 23, CBD Belapur, Navi Mumbai',
    latitude: 19.0222,
    longitude: 73.0368,
    is_24_7: true,
    languages_spoken: ['English', 'Hindi', 'Marathi', 'Arabic'],
    notes: 'International tourist medical liaison, cardiac ICU, burn and multi-speciality trauma center.',
  },
  {
    id: 'srv-3',
    name: 'MGM New Bombay Hospital',
    category: 'hospital',
    phone: '+91 22 2782 5000',
    address: 'Sector 3, Vashi, Navi Mumbai',
    latitude: 19.0734,
    longitude: 72.9980,
    is_24_7: true,
    languages_spoken: ['English', 'Hindi', 'Marathi'],
    notes: '24/7 emergency casualty ward, pathology lab, ambulance dispatch.',
  },
  {
    id: 'srv-4',
    name: 'DY Patil Multi-Speciality Hospital',
    category: 'hospital',
    phone: '+91 22 2770 0000',
    address: 'Sector 5, Nerul, Navi Mumbai',
    latitude: 19.0435,
    longitude: 73.0165,
    is_24_7: true,
    languages_spoken: ['English', 'Hindi', 'Marathi'],
    notes: 'Premier state emergency center, advanced trauma facilities, English-speaking medical staff.',
  },
  {
    id: 'srv-5',
    name: 'Vashi Police Station',
    category: 'police',
    phone: '+91 22 2789 0100',
    address: 'Sector 17, Vashi, Navi Mumbai',
    latitude: 19.0755,
    longitude: 72.9990,
    is_24_7: true,
    languages_spoken: ['English', 'Hindi', 'Marathi'],
    notes: 'Rapid sector patrol dispatch, central control room monitoring.',
  },
  {
    id: 'srv-6',
    name: '24-Hour Apollo Emergency Pharmacy',
    category: 'pharmacy',
    phone: '+91 22 2771 1234',
    address: 'Palm Beach Galleria, Sector 19D, Vashi, Navi Mumbai',
    latitude: 19.0680,
    longitude: 73.0030,
    is_24_7: true,
    languages_spoken: ['English', 'Hindi', 'Marathi'],
    notes: 'Emergency prescriptions, asthma inhalers, first-aid medical supplies.',
  },
];

export const INITIAL_INCIDENTS: Incident[] = [
  {
    id: 'inc-1',
    incident_code: 'INC-7801',
    reporter_id: '11111111-1111-1111-1111-111111111111',
    reporter_name: 'Elena Rostova',
    reporter_phone: '+1 (555) 234-8901',
    is_sos: true,
    category: 'medical_emergency',
    priority: 'critical',
    status: 'assigned',
    title: 'SOS Emergency: Severe Acute Allergic Reaction',
    description: 'Tourist triggered SOS near Inorbit Mall Vashi. Experiencing acute shortness of breath and throat swelling. Ventolin inhaler exhausted.',
    latitude: 19.0665,
    longitude: 72.9985,
    address: 'Inorbit Mall Promenade, Sector 30A, Vashi, Navi Mumbai',
    landmark: 'Near Main Entrance Gate 2 opposite Vashi Station',
    responder_id: 'resp-1',
    responder_name: 'Unit Alpha-1 (Officer Vikram Patil)',
    responder_notes: 'Motor patrol unit dispatched from Vashi Sector 17. ETA ~ 3 mins. First-aid oxygen kit on board.',
    eta_minutes: 3,
    created_at: new Date(Date.now() - 6 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
    updates: [
      {
        id: 'upd-1',
        incident_id: 'inc-1',
        updater_name: 'Automated SOS Trigger',
        updater_role: 'tourist',
        new_status: 'received',
        notes: 'SOS emergency triggered via GPS coordinate capture in Navi Mumbai.',
        created_at: new Date(Date.now() - 6 * 60 * 1000).toISOString(),
      },
      {
        id: 'upd-2',
        incident_id: 'inc-1',
        updater_name: 'Inspector Rajiv Shinde',
        updater_role: 'authority',
        previous_status: 'received',
        new_status: 'reviewing',
        notes: 'Triaged as Critical priority. Alerted nearest patrol and Apollo emergency ambulance.',
        created_at: new Date(Date.now() - 4 * 60 * 1000).toISOString(),
      },
      {
        id: 'upd-3',
        incident_id: 'inc-1',
        updater_name: 'Inspector Rajiv Shinde',
        updater_role: 'authority',
        previous_status: 'reviewing',
        new_status: 'assigned',
        notes: 'Assigned to Unit Alpha-1 (Officer Vikram Patil).',
        created_at: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
      },
    ],
  },
  {
    id: 'inc-2',
    incident_code: 'INC-7802',
    reporter_name: 'Marcus Henderson',
    reporter_phone: '+44 7700 900456',
    is_sos: false,
    category: 'theft',
    priority: 'high',
    status: 'reviewing',
    title: 'Bag Snatched Containing Passport & Travel Wallet',
    description: 'Black backpack snatched near Seawoods Grand Central concourse by two individuals heading toward Palm Beach Road.',
    latitude: 19.0180,
    longitude: 73.0180,
    address: 'Grand Central Mall Plaza, Sector 40, Seawoods, Nerul, Navi Mumbai',
    landmark: 'Outside Seawoods Railway Station West Exit',
    created_at: new Date(Date.now() - 22 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    updates: [
      {
        id: 'upd-2-1',
        incident_id: 'inc-2',
        updater_name: 'Marcus Henderson',
        updater_role: 'tourist',
        new_status: 'received',
        notes: 'Report filed with CCTV time marker and suspect direction description.',
        created_at: new Date(Date.now() - 22 * 60 * 1000).toISOString(),
      },
      {
        id: 'upd-2-2',
        incident_id: 'inc-2',
        updater_name: 'Inspector Rajiv Shinde',
        updater_role: 'authority',
        previous_status: 'received',
        new_status: 'reviewing',
        notes: 'Accessing Navi Mumbai Smart City CCTV feed on Palm Beach Road junction.',
        created_at: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
      },
    ],
  },
  {
    id: 'inc-3',
    incident_code: 'INC-7798',
    reporter_name: 'Aiko Tanaka',
    reporter_phone: '+81 90 1234 5678',
    is_sos: false,
    category: 'lost_person',
    priority: 'high',
    status: 'resolved',
    title: 'Separated Tour Member Reunited',
    description: 'Elderly tour participant separated from guided group during visit to Central Park Kharghar.',
    latitude: 19.0480,
    longitude: 73.0680,
    address: 'Central Park Main Amphitheatre, Sector 23, Kharghar, Navi Mumbai',
    responder_id: 'resp-3',
    responder_name: 'Palm Beach Highway Patrol Unit 4',
    resolution_notes: 'Located safe at Kharghar Tourist Information Kiosk. Rejoined tour leader Rajesh Patil.',
    created_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    resolved_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
];

export const INITIAL_LOST_FOUND: LostFoundItem[] = [
  {
    id: 'lf-1',
    item_code: 'LF-3041',
    item_type: 'lost',
    title: 'Sony Alpha A7 IV Camera in Tan Leather Case',
    description: 'Black mirrorless camera with 24-70mm GM lens. Left on sea-facing bench at Sagar Vihar promenade.',
    category: 'electronics',
    location_name: 'Sagar Vihar Promenade, Sector 8, Vashi, Navi Mumbai',
    latitude: 19.0810,
    longitude: 72.9860,
    date_lost_or_found: new Date(Date.now() - 86400000).toISOString().split('T')[0],
    reporter_name: 'Elena Rostova',
    contact_phone: '+1 (555) 234-8901',
    contact_email: 'elena.rostova@example.com',
    status: 'reported_lost',
    created_at: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'lf-2',
    item_code: 'LF-3042',
    item_type: 'found',
    title: 'Brown Bellroy Leather Travel Wallet with German Driver License',
    description: 'Found on seat at Vashi Railway Station Concourse Gate 2. Contains transit smartcard, euro currency, and ID for Thomas Weber.',
    category: 'wallet/money',
    location_name: 'Vashi Railway Station Concourse, Sector 30A, Navi Mumbai',
    latitude: 19.0650,
    longitude: 72.9990,
    date_lost_or_found: new Date().toISOString().split('T')[0],
    reporter_name: 'Vashi Railway Transit Security Desk',
    contact_phone: '+91 22 2789 0100',
    contact_email: 'lostproperty@navimumbaitransit.gov.in',
    status: 'reported_found',
    created_at: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
  },
  {
    id: 'lf-3',
    item_code: 'LF-3039',
    item_type: 'found',
    title: 'Silver Apple iPad Pro 11" with Blue Smart Folio',
    description: 'Handed over by taxi driver at Seawoods Grand Central dropoff. In clean condition, lockscreen shows travel itinerary.',
    category: 'electronics',
    location_name: 'Seawoods Grand Central Prepaid Taxi Counter, Nerul, Navi Mumbai',
    latitude: 19.0180,
    longitude: 73.0180,
    date_lost_or_found: new Date(Date.now() - 2 * 86400000).toISOString().split('T')[0],
    reporter_name: 'Seawoods Mall Tourist Assistance Desk',
    contact_phone: '+91 22 6280 1100',
    status: 'reported_found',
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
];

export const INITIAL_TOURIST_GROUPS: TouristGroup[] = [
  {
    id: 'grp-1',
    name: 'Navi Mumbai Coastal & Heritage Discovery - Batch 14',
    group_code: 'NM-9421',
    guide_name: 'Rajesh Patil (Govt Certified Guide #441)',
    guide_phone: '+91 98450 12345',
    hotel_or_agency: 'Incredible Maharashtra Expeditions Ltd.',
    description: 'Guided tour across historic Belapur Fort, Sagar Vihar coastline, Kharghar hills, and botanical gardens with dedicated safety escort.',
    max_members: 25,
    members_count: 14,
    created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
  },
];

export const INITIAL_GROUP_MEMBERS: GroupMember[] = [
  {
    id: 'gm-1',
    group_id: 'grp-1',
    user_id: '11111111-1111-1111-1111-111111111111',
    member_name: 'Elena Rostova (You)',
    member_phone: '+1 (555) 234-8901',
    is_safe: true,
    share_location: true,
    last_lat: 19.0330,
    last_lng: 73.0297,
    last_checkin_at: new Date().toISOString(),
    joined_at: new Date(Date.now() - 3 * 86400000).toISOString(),
  },
  {
    id: 'gm-2',
    group_id: 'grp-1',
    user_id: 'usr-2',
    member_name: 'Liam Vance (Guide Assistant)',
    member_phone: '+44 7891 002233',
    is_safe: true,
    share_location: true,
    last_lat: 19.0340,
    last_lng: 73.0305,
    last_checkin_at: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    joined_at: new Date(Date.now() - 3 * 86400000).toISOString(),
  },
  {
    id: 'gm-3',
    group_id: 'grp-1',
    user_id: 'usr-3',
    member_name: 'Sophia Chen',
    member_phone: '+1 (415) 880-9922',
    is_safe: true,
    share_location: true,
    last_lat: 19.0325,
    last_lng: 73.0290,
    last_checkin_at: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    joined_at: new Date(Date.now() - 3 * 86400000).toISOString(),
  },
];

export const INITIAL_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'notif-1',
    title: 'SOS Response Dispatched',
    message: 'Unit Alpha-1 (Officer Vikram Patil) has been assigned to your medical alert in Vashi. ETA ~ 3 mins.',
    type: 'sos_alert',
    is_read: false,
    related_incident_id: 'inc-1',
    created_at: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
  },
  {
    id: 'notif-2',
    title: 'Zone Advisory: Approaching High Crowd Area',
    message: 'You are within 500m of Kharghar Hills Monsoon Advisory Zone. Keep to designated paths.',
    type: 'zone_warning',
    is_read: false,
    created_at: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
  },
  {
    id: 'notif-3',
    title: 'Tour Guide Safety Broadcast',
    message: 'Rajesh Patil: Group gathering at Sagar Vihar Promenade Sunset Deck at 6:00 PM.',
    type: 'group_alert',
    is_read: true,
    created_at: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
  },
];
